language: ruby
sudo: false
rvm:
  - 2.4
  - 2.5
  - 2.6
gemfile:
  - gemfiles/4.2.gemfile
  - gemfiles/5.1.gemfile
  - gemfiles/5.2.gemfile
before_install:
  - "gem install bundler -v=1.17"
before_script:
  - "bundle install"
script: "bundle exec rake clean test"
