language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
gemfile:
  - gemfiles/2.3.gemfile
  - gemfiles/3.0.gemfile
  - gemfiles/3.1.gemfile
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile
before_install:
  - "gem install bundler -v=1.3.0"
before_script:
  - "bundle install"
script: "bundle exec rake clean test"
