language: ruby

cache: bundler

rvm:
  - 2.4
  - 2.5
  - 2.6

gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile

before_install:
  - gem update --system
  # Rails 4.2 doesn't support bundler 2.0, so we need to lock bundler to
  # v1.17.3. This is just for Ruby 2.5 which ships with bundler 2.x on Travis
  # CI while Ruby 2.6 does not.
  - yes | rvm @global do gem install bundler -v 1.17.3 || true

matrix:
  exclude:
    # Rails 6 requires Ruby 2.5+
    - gemfile: gemfiles/rails_6.0.gemfile
      rvm: 2.4
